package constants;

public enum ErrorCode {

    NOT_EXIST_MESSAGE,
    INVALID_SEPARATOR,
    INVALID_INPUT,
    INVALID_SIZE,
    INVALID_BET_AMOUNT,
    DUPLICATE_NAME,
    RESERVED_NAME,
    BLANK_VALUE,
    EMPTY_CARD,
    INVALID_COMMAND,
}
