package domain;

public enum ExceptionCode {
    INVALID_DRAWING_CARD_REQUEST,
    INVALID_NUMBER_OF_PLAYER,
    NAME_IS_EMPTY,
    NAME_IS_NULL,
    NAME_IS_DEALER,
    NAME_IS_DUPLICATED,
    NAME_CONTAINS_COMMA,
    INVALID_NAME_LENGTH,
    NO_DEALER,
    LEAK_BET_AMOUNT,
    TYPE_MISS_MATCH_BET_AMOUNT

}
